language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: AKqlcQu7CxZJCnrGR233thdD/tzMlODkJZRAupaNdA6uE0cdHTwUMlUQwwinE2REwrj47oEBb+3LG7m4E+PNc8K+lqMuTqTYNbv0juIk5zrkHx/tel+PQ54fyUxFm0ofdZW3D8oaCibXWNdWP5Q1njZHfOPERr5NojTkQZv7+rxFOFsfKLQ/8yFzomxcuOrT3ATJsLd0XqjqvQ6CsOrNe1wrbR/dSXWwz9j1jJK8+AoqO5q15d08FS5Vy6zZ+2Jxzslo02KlS2iRDsRODInvRhY20XwIVHk8q/QlX+0aLEQ6kKLdAfbSVwH6StZ272+ZMrdv0H1BGQzti30CqASgrOk3bkLBrUqrj8AXpHt3WQ1kXsE9De9guWzsufupf4Oani7+81g7WDn4FMBEce6nV6d+2azTucFwEA86zSwbP5R9nF0CNC1CNPfnCd7nv5e2Dc8UTq5snGMmShu2g0+DEv7m2xR7EoY6r00mJrhPsJb8KbgnBJCYEevgY8hTDh8j6Pp6ou8vPjM7ZhCh896Mbwcvt4CdVNHu39JyWh863+qenAOKrRrXFX3VXkDye4XEF7eZHM98qRf+F2uYonJWTGVmQN6yzrdYB3ajnHeLelIz6oHor0NDTN6HcmZlSdXzRM3zIvXs0ZvYSddeMKZTw4fevl1sniuKJ8SOnQYNM1U=
  app: whispering-shore-12283
  on:
    repo: rrustia/node-shopping-list-integration-tests
